/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as Page2RouteImport } from './routes/$page2'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodoListIndexRouteImport } from './routes/todoList/index'
import { Route as SueIndexRouteImport } from './routes/sue/index'
import { Route as FormIndexRouteImport } from './routes/form/index'
import { Route as TodoListContentRouteImport } from './routes/todoList/$content'
import { Route as pagesNewsRouteImport } from './routes/(pages)/news'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const Page2Route = Page2RouteImport.update({
  id: '/$page2',
  path: '/$page2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoListIndexRoute = TodoListIndexRouteImport.update({
  id: '/todoList/',
  path: '/todoList/',
  getParentRoute: () => rootRouteImport,
} as any)
const SueIndexRoute = SueIndexRouteImport.update({
  id: '/sue/',
  path: '/sue/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormIndexRoute = FormIndexRouteImport.update({
  id: '/form/',
  path: '/form/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoListContentRoute = TodoListContentRouteImport.update({
  id: '/todoList/$content',
  path: '/todoList/$content',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesNewsRoute = pagesNewsRouteImport.update({
  id: '/(pages)/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$page2': typeof Page2Route
  '/about': typeof AboutRoute
  '/news': typeof pagesNewsRoute
  '/todoList/$content': typeof TodoListContentRoute
  '/form/': typeof FormIndexRoute
  '/sue/': typeof SueIndexRoute
  '/todoList/': typeof TodoListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$page2': typeof Page2Route
  '/about': typeof AboutRoute
  '/news': typeof pagesNewsRoute
  '/todoList/$content': typeof TodoListContentRoute
  '/form': typeof FormIndexRoute
  '/sue': typeof SueIndexRoute
  '/todoList': typeof TodoListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$page2': typeof Page2Route
  '/about': typeof AboutRoute
  '/(pages)/news': typeof pagesNewsRoute
  '/todoList/$content': typeof TodoListContentRoute
  '/form/': typeof FormIndexRoute
  '/sue/': typeof SueIndexRoute
  '/todoList/': typeof TodoListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$page2'
    | '/about'
    | '/news'
    | '/todoList/$content'
    | '/form/'
    | '/sue/'
    | '/todoList/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$page2'
    | '/about'
    | '/news'
    | '/todoList/$content'
    | '/form'
    | '/sue'
    | '/todoList'
  id:
    | '__root__'
    | '/'
    | '/$page2'
    | '/about'
    | '/(pages)/news'
    | '/todoList/$content'
    | '/form/'
    | '/sue/'
    | '/todoList/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Page2Route: typeof Page2Route
  AboutRoute: typeof AboutRoute
  pagesNewsRoute: typeof pagesNewsRoute
  TodoListContentRoute: typeof TodoListContentRoute
  FormIndexRoute: typeof FormIndexRoute
  SueIndexRoute: typeof SueIndexRoute
  TodoListIndexRoute: typeof TodoListIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$page2': {
      id: '/$page2'
      path: '/$page2'
      fullPath: '/$page2'
      preLoaderRoute: typeof Page2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todoList/': {
      id: '/todoList/'
      path: '/todoList'
      fullPath: '/todoList/'
      preLoaderRoute: typeof TodoListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sue/': {
      id: '/sue/'
      path: '/sue'
      fullPath: '/sue/'
      preLoaderRoute: typeof SueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/': {
      id: '/form/'
      path: '/form'
      fullPath: '/form/'
      preLoaderRoute: typeof FormIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todoList/$content': {
      id: '/todoList/$content'
      path: '/todoList/$content'
      fullPath: '/todoList/$content'
      preLoaderRoute: typeof TodoListContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/news': {
      id: '/(pages)/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof pagesNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Page2Route: Page2Route,
  AboutRoute: AboutRoute,
  pagesNewsRoute: pagesNewsRoute,
  TodoListContentRoute: TodoListContentRoute,
  FormIndexRoute: FormIndexRoute,
  SueIndexRoute: SueIndexRoute,
  TodoListIndexRoute: TodoListIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
